---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/mo3m3n/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-plnsvc/bump-vgpj
