apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-components-staging
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: argo-cd-apps/overlays/staging
    repoURL: https://github.com/mo3m3n/infra-deployments.git
    targetRevision: preview

  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc

  syncPolicy:

    automated: 
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true
