# Reset securityContext
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-chains-controller
  namespace: tekton-chains
spec:
  template:
    spec:
      containers:
        - name: tekton-chains-controller
          securityContext:
            allowPrivilegeEscalation: false
            $patch: replace
