resources:
  - https://github.com/redhat-appstudio/sprayproxy/config?ref=076942559b739729c156b3d64f87efda1731ab90

namespace: sprayproxy

images:
  - name: ko://github.com/redhat-appstudio/sprayproxy
    newName: quay.io/redhat-appstudio/sprayproxy
    newTag: 076942559b739729c156b3d64f87efda1731ab90

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: backends
    literals:
      - SPRAYPROXY_SERVER_BACKENDS=pipelines-as-code-controller-pipelines-as-code.apps.stone-stg-m01.1ion.p1.openshiftapps.com pipelines-as-code-controller-pipelines-as-code.apps.stone-stg-rh01.0fk9.p1.openshiftapps.com

patches:
  - path: add-backends-configmap.yml
    target:
      name: sprayproxy
      group: apps
      version: v1
